#!/bin/bash
# Ubuntu 20.04 LTS

# Update repos
sudo apt update -y

# Install SFML
sudo apt install libsfml-dev -y

# Install OpenCV
sudo apt install libopencv-dev -y

# Install OpenGL + FreeGLUT3
sudo apt install freeglut3-dev -y

# Install QT5
sudo apt install qt5-default -y

# Intall Protobuf
sudo apt install libprotobuf -y
sudo apt install protobuf-compiler -y