// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrapper.proto

#ifndef PROTOBUF_INCLUDED_wrapper_2eproto
#define PROTOBUF_INCLUDED_wrapper_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "messages_robocup_ssl_detection.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_wrapper_2eproto 

namespace protobuf_wrapper_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_wrapper_2eproto
namespace vision {
class SSL_WrapperPacket;
class SSL_WrapperPacketDefaultTypeInternal;
extern SSL_WrapperPacketDefaultTypeInternal _SSL_WrapperPacket_default_instance_;
}  // namespace vision
namespace google {
namespace protobuf {
template<> ::vision::SSL_WrapperPacket* Arena::CreateMaybeMessage<::vision::SSL_WrapperPacket>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace vision {

// ===================================================================

class SSL_WrapperPacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:vision.SSL_WrapperPacket) */ {
 public:
  SSL_WrapperPacket();
  virtual ~SSL_WrapperPacket();

  SSL_WrapperPacket(const SSL_WrapperPacket& from);

  inline SSL_WrapperPacket& operator=(const SSL_WrapperPacket& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SSL_WrapperPacket(SSL_WrapperPacket&& from) noexcept
    : SSL_WrapperPacket() {
    *this = ::std::move(from);
  }

  inline SSL_WrapperPacket& operator=(SSL_WrapperPacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SSL_WrapperPacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SSL_WrapperPacket* internal_default_instance() {
    return reinterpret_cast<const SSL_WrapperPacket*>(
               &_SSL_WrapperPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SSL_WrapperPacket* other);
  friend void swap(SSL_WrapperPacket& a, SSL_WrapperPacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SSL_WrapperPacket* New() const final {
    return CreateMaybeMessage<SSL_WrapperPacket>(NULL);
  }

  SSL_WrapperPacket* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SSL_WrapperPacket>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SSL_WrapperPacket& from);
  void MergeFrom(const SSL_WrapperPacket& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSL_WrapperPacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .SSL_DetectionFrame detection = 1;
  bool has_detection() const;
  void clear_detection();
  static const int kDetectionFieldNumber = 1;
  private:
  const ::SSL_DetectionFrame& _internal_detection() const;
  public:
  const ::SSL_DetectionFrame& detection() const;
  ::SSL_DetectionFrame* release_detection();
  ::SSL_DetectionFrame* mutable_detection();
  void set_allocated_detection(::SSL_DetectionFrame* detection);

  // @@protoc_insertion_point(class_scope:vision.SSL_WrapperPacket)
 private:
  void set_has_detection();
  void clear_has_detection();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::SSL_DetectionFrame* detection_;
  friend struct ::protobuf_wrapper_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SSL_WrapperPacket

// optional .SSL_DetectionFrame detection = 1;
inline bool SSL_WrapperPacket::has_detection() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SSL_WrapperPacket::set_has_detection() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SSL_WrapperPacket::clear_has_detection() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::_internal_detection() const {
  return *detection_;
}
inline const ::SSL_DetectionFrame& SSL_WrapperPacket::detection() const {
  const ::SSL_DetectionFrame* p = detection_;
  // @@protoc_insertion_point(field_get:vision.SSL_WrapperPacket.detection)
  return p != NULL ? *p : *reinterpret_cast<const ::SSL_DetectionFrame*>(
      &::_SSL_DetectionFrame_default_instance_);
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::release_detection() {
  // @@protoc_insertion_point(field_release:vision.SSL_WrapperPacket.detection)
  clear_has_detection();
  ::SSL_DetectionFrame* temp = detection_;
  detection_ = NULL;
  return temp;
}
inline ::SSL_DetectionFrame* SSL_WrapperPacket::mutable_detection() {
  set_has_detection();
  if (detection_ == NULL) {
    auto* p = CreateMaybeMessage<::SSL_DetectionFrame>(GetArenaNoVirtual());
    detection_ = p;
  }
  // @@protoc_insertion_point(field_mutable:vision.SSL_WrapperPacket.detection)
  return detection_;
}
inline void SSL_WrapperPacket::set_allocated_detection(::SSL_DetectionFrame* detection) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(detection_);
  }
  if (detection) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      detection = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, detection, submessage_arena);
    }
    set_has_detection();
  } else {
    clear_has_detection();
  }
  detection_ = detection;
  // @@protoc_insertion_point(field_set_allocated:vision.SSL_WrapperPacket.detection)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace vision

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_wrapper_2eproto
